config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  namespace :admin do
    root to: 'statistics#index'

    resources :users
    resources :groups, except: [:show]
    resources :statistics, only: [:index]
  end

  resources :surveys do
    collection do
      get 'manage', to: :manage
    end
    put :close
    resources :answers, only: [:index, :show, :create]
  end

  resources :your_answers, only: [:index, :show]

  post 'contact', to: 'contact#create'

  get 'profile', to: 'profiles#edit'
  put 'profile', to: 'profiles#update'

  get 'autocomplete/groups', to: 'autocomplete#groups'
  get 'autocomplete/users', to: 'autocomplete#users'
end

app/views/shared/_contact_modal.html.erb
<div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"><%= t('.contact_admin') %></h4>
      </div>

      <form accept-charset='UTF-8' data-action='/contact'>
        <div class="modal-body">
          <div class="dialog-error dialog-message hidden-none"><%= t('.error') %></div>
          <div class="dialog-success dialog-message hidden-none"><%= t('.success') %></div>

          <input type='text' placeholder="<%= t('.email_prompt') %>" id='contact-email' class='form-control'>
          <textarea id='contact-body' placeholder="<%= t('.prompt') %>" class='form-control' rows='5'></textarea>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('.cancel') %></button>
          <button type="button" class="btn btn-primary send"><%= t('.send') %></button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/shared/_profile_dropdown.html.erb
<ul class="nav navbar-top-links navbar-right">
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
  </a>
  <ul class="dropdown-menu dropdown-user">
    <% if current_user %>
      <li>
        <%= link_to profile_path do %>
          <i class="fa fa-user fa-fw"></i> <%= t('.user_profile') %>
        <% end %>
      </li>
      <li class="divider"></li>
    <% end %>
    <li>
      <% if current_user %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out fa-fw"></i> Logout
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="fa fa-sign-out fa-fw"></i> Login
        <% end %>
      <% end %>
    </li>
  </ul>
</li>
</ul>

app/views/shared/_topmenu.html.erb
<div class="navbar-collapse collapse navbar-responsive-collapse">
  <ul class="nav navbar-nav">
    <% if Survey.initializable_by?(current_user) %>
      <li><%= link_to t('shared.topmenu.new_survey'), new_survey_path %></li>
      <li><%= link_to t('shared.topmenu.manage_surveys'), manage_surveys_path %></li>
    <% end %>
    <% if current_user %>
      <li><%= link_to t('shared.topmenu.surveys_list'), surveys_path %></li>
      <li><%= link_to t('shared.topmenu.your_answers'), your_answers_path %></li>
    <% end %>
    <% if current_user.try(:admin?) %>
      <li><%= link_to t('.admin_panel'), admin_statistics_path  %></li>
    <% end %>
  </ul>
</div>