config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  namespace :admin do
    root to: 'statistics#index'

    resources :users
    resources :groups, except: [:show]
    resources :statistics, only: [:index]
  end

  resources :surveys do
    collection do
      get 'manage', to: :manage
    end
    put :close
    resources :answers, only: [:index, :show, :create]
  end

  resources :your_answers, only: [:index, :show]

  post 'contact', to: 'contact#create'

  get 'profile', to: 'profiles#edit'
  put 'profile', to: 'profiles#update'

  get 'autocomplete/groups', to: 'autocomplete#groups'
  get 'autocomplete/users', to: 'autocomplete#users'
end

app/controllers/admin/statistics_controller.rb
module Admin
  class StatisticsController < BaseController
    def index

    end
  end
end

app/views/admin/statistics/index.html.erb
<div class="row">
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3"><i class="fa fa-smile-o fa-5x"></i></div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= User.without_deleted.count %></div>
            <div><%= t('.users_total') %></div>
          </div>
        </div>
      </div>
      <a href="<%= admin_users_path %>">
        <div class="panel-footer"><span class="pull-left"><%= t('.view_details') %></span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3"><i class="fa fa-users fa-5x"></i></div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= Group.count %></div>
            <div><%= t('.groups_total') %></div>
          </div>
        </div>
      </div>
      <a href="<%= admin_groups_path %>">
        <div class="panel-footer"><span class="pull-left"><%= t('.view_details') %></span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3"><i class="fa fa-check-square-o fa-5x"></i></div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= Survey.count %></div>
            <div><%= t('.surveys_total') %></div>
          </div>
        </div>
      </div>
      <a href="#surveys-chart">
        <div class="panel-footer"><span class="pull-left"><%= t('.view_details') %></span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3"><i class="fa fa-tasks fa-5x"></i></div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= SurveyAnswer.count %></div>
            <div><%= t('.survey_answers_total') %></div>
          </div>
        </div>
      </div>
      <a href="#survey-answers-chart">
        <div class="panel-footer"><span class="pull-left"><%= t('.view_details') %></span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>

<div class="col-xs-12">
  <h3><%= t('.new_users') %></h3>
  <%= line_chart User.group_by_day(:created_at, format: "%B %d, %Y").count, discrete: true %>

  <h3 id="surveys-chart"><%= t('.new_surveys') %></h3>
  <%= line_chart Survey.group_by_day(:created_at, format: "%B %d, %Y").count, discrete: true %>

  <h3 id="survey-answers-chart"><%= t('.new_survey_answers') %></h3>
  <%= line_chart SurveyAnswer.group_by_day(:created_at, format: "%B %d, %Y").count, discrete: true %>
</div>