config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  namespace :admin do
    root to: 'statistics#index'

    resources :users
    resources :groups, except: [:show]
    resources :statistics, only: [:index]
  end

  resources :surveys do
    collection do
      get 'manage', to: :manage
    end
    put :close
    resources :answers, only: [:index, :show, :create]
  end

  resources :your_answers, only: [:index, :show]

  post 'contact', to: 'contact#create'

  get 'profile', to: 'profiles#edit'
  put 'profile', to: 'profiles#update'

  get 'autocomplete/groups', to: 'autocomplete#groups'
  get 'autocomplete/users', to: 'autocomplete#users'
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', inverse_of: :surveys

  default_scope { where(:deleted_at => nil) }

  has_many :question_groups,
    inverse_of: :survey,
    dependent: :destroy
  has_many :questions,
    through: :question_groups,
    dependent: :destroy
  has_many :survey_answers, dependent: :destroy

  has_and_belongs_to_many :groups
  alias_method :allowed_groups, :groups

  has_and_belongs_to_many :users
  alias_method :allowed_users, :users

  accepts_nested_attributes_for :question_groups, allow_destroy: true

  validates :title, presence: true, length: { maximum: 50 }
  validates :owner, presence: true
  validates :question_groups, presence: { message: "Survey must contain at least one section" }
  validate :validate_activity_period

  scope :answerable_by, ->(user) {
    ids = select(:id)
    .joins("LEFT JOIN surveys_users ON surveys_users.survey_id = surveys.id LEFT JOIN users ON users.id = surveys_users.user_id
           LEFT JOIN groups_surveys ON groups_surveys.survey_id = surveys.id LEFT JOIN groups ON groups.id = groups_surveys.group_id
           LEFT JOIN groups_users ON groups_users.group_id = groups_surveys.group_id")
    .where("public = true
            OR surveys_users.user_id = #{user.id}
            OR groups_users.user_id = #{user.id}")
    .distinct

    where(id: ids)
  }

  scope :active, -> do
    where(
      "COALESCE(active_since <= :now, TRUE) AND COALESCE(active_until >= :now, TRUE)",
      now: DateTime.now
    )
  end

  scope :editable_by, ->(user) {
    return if user.admin?

    where(owner: user)
  }

  scope :order_by, -> (field, order = :asc) do
    Sorter.new(all, field, order).sort
  end

  attr_reader :token_user_ids, :token_group_ids

  def ongoing?
    (active_since.blank? || active_since <= DateTime.now) &&
      (active_until.blank? || active_until >= DateTime.now)
  end

  def close
    if ongoing?
      update_attribute(:active_until, DateTime.now)
    end
  end

  def total_answer_limit_reached?
    max_answers.present? && survey_answers.count >= max_answers
  end

  def answer_limit_per_user_reached?(user_id)
    max_answers_per_user.present? && survey_answers.where(user_id: user_id).count >= max_answers_per_user
  end

  def token_user_ids=(ids)
    self.user_ids = ids.split(',')
  end

  def token_group_ids=(ids)
    self.group_ids = ids.split(',')
  end

  def editable_by?(user)
    owner == user || user.admin?
  end

  def answerable_by?(user)
    self.public || user_allowed?(user) || user_in_allowed_groups?(user)
  end

  def self.initializable_by?(user)
    user && (user.admin? || user.survey_owner?)
  end

  private

  def user_allowed?(user)
    allowed_users.include?(user)
  end

  def user_in_allowed_groups?(user)
    (allowed_groups & user.groups).present?
  end

  def validate_activity_period
    if active_since.present? && active_until.present? && active_since > active_until
      errors.add(:active_since, :must_be_before_active_until)
    end
  end
end

app/models/survey/sorter.rb
class Survey
	class Sorter
    def initialize(relation, sort_field, sort_order)
      self.relation = relation
      self.sort_field = sort_field.to_sym
      self.sort_order = sort_order.to_sym
    end

    attr_accessor :relation, :sort_field, :sort_order

    BASIC_ATTRIBUTES = Survey.new.attributes.keys.map(&:to_sym)

    def sort
      if BASIC_ATTRIBUTES.include?(sort_field)
        relation.order("#{sort_field}" => sort_order)
      elsif sort_field == :owner_email
        relation.joins('JOIN users u ON u.id=surveys.owner_id').order("u.email #{sort_order}")
      else
        relation
      end
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  include SurveyFilters

  before_filter :disallow_guest
  before_filter :initialize_and_authorize_survey_for_edit, only: [:edit, :update, :destroy, :close]
  before_filter :initialize_and_authorize_survey_for_answer, only: [:show]

  helper_method :sort_field, :sort_order

  def index
    @surveys = Survey.includes(:owner).answerable_by(current_user).active.order_by(sort_field, sort_order).paginate(page: page, per_page: per_page)
  end

  def new
    initialize_new_survey
  end

  def create
    @survey = current_user.surveys.new(survey_params)

    if !@survey.save
      render :new
      flash[:error] = I18n.t('surveys.create.failure')

      return
    end
  end

  def show
    @answer = @survey.survey_answers.build(user: current_user)
  end

  def edit
  end

  def update
    if @survey.update(survey_params)
      flash[:success] = I18n.t('surveys.update.success')
      redirect_to edit_survey_path(@survey)
    else
      flash[:error] = I18n.t('surveys.update.failure')
      render :edit
    end
  end

  def destroy
    @survey.update_attribute(:deleted_at, DateTime.now)
    flash[:success] = I18n.t('surveys.destroy.success')

    redirect_to manage_surveys_path
  end

  def manage
    @surveys = Survey.editable_by(current_user).order(created_at: :desc).paginate(page: params[:page])
  end

  def close
    @survey.close
    flash[:success] = I18n.t('surveys.close.success')

    redirect_to manage_surveys_path
  end

  private

  def initialize_new_survey
    raise CanCan::AccessDenied unless Survey.initializable_by?(current_user)

    @survey = current_user.surveys.new
    @survey.question_groups.build(position: 0)
    @survey.question_groups.first.questions.build(question_type: :text, position: 0)
  end

  def survey_params
    params.require(:survey).permit(:title, :public, :token_group_ids, :token_user_ids, :active_since, :active_until, :max_answers, :max_answers_per_user,
      question_groups_attributes: [:id, :_destroy, :title, :position, questions_attributes:
        [:id, :_destroy, :text, :question_type, :position, :mandatory, options_attributes:
          [:id, :_destroy, :text, :position, :custom]
        ]
      ]
    )
  end

  def sort_field
    params[:sort_field] || :created_at
  end

  def sort_order
    params[:sort_order] || :desc
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def activity_dates_subtitle(survey)
  	now = DateTime.now
    text = ''
    html_class = 'survey-subtitle'
  	if survey.active_since.present? && survey.active_since > now
  		text = t('surveys.show.survey_starts_at', date: survey.active_since)
      html_class += ' inactive'
  	elsif (survey.active_since.blank? || survey.active_since <= now) &&
  		survey.active_until.present? && survey.active_until >= now
  		text = t('surveys.show.active_until', to: survey.active_until)
  	elsif survey.active_until.present? && survey.active_until < now
  	  text = t('surveys.show.survey_ended', date: survey.active_until)
      html_class += ' inactive'
    end

    text.present? ? content_tag(:h4, text, class: html_class) : nil
  end

  def partial_for_option(question_type, option)
    custom = option.custom? ? 'custom_' : ''
    "surveys/create/options/#{custom}#{question_type}"
  end
end

app/views/surveys/create.html.erb
<div>
  <h3><%= t('surveys.create.header') %></h3>
  <%= t('surveys.create.you_can') %>
  <ul>
    <li><%= t('surveys.create.answer') %> <%= link_to t('surveys.create.here'), survey_path(@survey) %></li>
    <li><%= t('surveys.create.edit') %> <%= link_to t('surveys.create.here'), edit_survey_path(@survey) %></li>
    <li><%= t('surveys.create.remove') %> <%= link_to t('surveys.create.here'), survey_path(@survey), method: :delete, data: { confirm: t('are_you_sure') } %></li>
    <li><%= t('surveys.create.see_results') %> <%= link_to t('surveys.create.here'), survey_answers_path(@survey) %></li>
  </ul>
</div>

app/views/surveys/destroy.html.erb
<div>
  <h3><%= t('surveys.destroy.header') %></h3>
</div>

app/views/surveys/edit.html.erb
<%= page_header t('.title'), tooltip: { title: t('.tooltip') } %>
<%= render 'surveys/create/form' %>

app/views/surveys/index.html.erb
<div>
  <%= page_header t('.available_surveys'), tooltip: { title: t('.tooltip') } %>

  <% if @surveys.empty? %>
    <h4><%= t('.no_surveys_message') %></h4>
  <% else %>
    <%= render partial: 'surveys/index/list' %>
  <% end %>
</div>

app/views/surveys/manage.html.erb
<div>
  <%= page_header t('.manage_surveys'), tooltip: { title: t('.tooltip') } %>
  <% if @surveys.empty? %>
    <h4>
      <%= t('.no_surveys_message') %><%= link_to t('surveys.create.here'), new_survey_path(@survey) %>
    </h4>
  <% else %>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th><%= sort_link t('.title'), :title %></th>
          <th><%= sort_link t('.created_at'), :created_at %></th>
          <th><%= sort_link t('.active_since'), :active_since %></th>
          <th><%= sort_link t('.active_until'), :active_until %></th>
          <th><%= t('surveys.manage.answers_header') %></th>
          <th><%= t('edit') %></th>
          <th><%= t('close') %></th>
          <th><%= t('delete') %></th>
        </tr>
        </thead>
        <tbody>
        <% @surveys.order(:id).each do |survey| %>
          <tr>
            <td><%= survey.title %></td>
            <td><%= survey.created_at %></td>
            <td><%= survey.active_since || '-' %></td>
            <td><%= survey.active_until || '-'%></td>
            <td><%= link_to t('surveys.manage.answers_link'), survey_answers_path(survey) %></td>
            <td><%= link_to t('edit'), edit_survey_path(survey) %></td>
            <td><%= survey.ongoing? ? link_to(t('close'), survey_close_path(survey), method: :put) : '-' %></td>
            <td><%= link_to t('delete'), survey_path(survey), method: :delete, data: { confirm: t('are_you_sure') } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= will_paginate @surveys, renderer: BootstrapPagination::Rails %>
    </div>
  <% end %>

</div>

app/views/surveys/new.html.erb
<%= page_header t('.title'), tooltip: { title: t('.tooltip') } %>
<%= render 'surveys/create/form' %>

app/views/surveys/show.html.erb
<div id='survey-answer'>
  <div class="page-header">
    <h1><%= @survey.title %></h1>
    <%= activity_dates_subtitle(@survey) %>
  </div>
  <% if @survey.total_answer_limit_reached? %>
    <h3 class='error'><%= t('errors.messages.total_answer_limit_reached') %></h3>
  <% elsif @survey.answer_limit_per_user_reached?(current_user.id) %>
    <h3 class='error'><%= t('errors.messages.answer_limit_per_user_reached') %></h3>
  <% elsif @survey.ongoing? %>
    <%= render partial: 'surveys/show/answer_form' %>
  <% end %>
</div>