config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  namespace :admin do
    root to: 'statistics#index'

    resources :users
    resources :groups, except: [:show]
    resources :statistics, only: [:index]
  end

  resources :surveys do
    collection do
      get 'manage', to: :manage
    end
    put :close
    resources :answers, only: [:index, :show, :create]
  end

  resources :your_answers, only: [:index, :show]

  post 'contact', to: 'contact#create'

  get 'profile', to: 'profiles#edit'
  put 'profile', to: 'profiles#update'

  get 'autocomplete/groups', to: 'autocomplete#groups'
  get 'autocomplete/users', to: 'autocomplete#users'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  TYPES = %w(User SurveyOwner AdminUser)
  DELETED_USER_EMAIL = '_deleted@user.account'

  has_and_belongs_to_many :groups
  has_many :surveys, foreign_key: 'owner_id', inverse_of: :owner
  has_many :survey_answers, dependent: :destroy

  accepts_nested_attributes_for :groups, allow_destroy: true

  validates :first_name, length: { maximum: 50 }
  validates :last_name, length: { maximum: 50 }

  scope :without_deleted, -> { where("users.email != '#{DELETED_USER_EMAIL}'") }

  def self.deleted_user
    User.create_with(password: 'test1234', password_confirmation: 'test1234').find_or_create_by(email: DELETED_USER_EMAIL)
  end

  def deleted_user?
    email == DELETED_USER_EMAIL
  end

  def admin?
    is_a?(AdminUser)
  end

  def survey_owner?
    is_a?(SurveyOwner)
  end

  def token_group_ids=(ids)
    self.group_ids = ids.first.split(',')
  end

  def autocomplete_format
    { id: id, name: "#{first_name} #{last_name} #{email}" }
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :set_user, only: [:edit, :update, :destroy]

    def index
      @users = User.paginate(page: page, per_page: per_page)
    end

    def new
      @user = User.new
    end

    def edit
    end

    def create
      @user = User.create(user_params)
      if @user.valid?
        redirect_to edit_admin_user_path(@user), notice: I18n.t('admin.users.created') and return
      else
        render :new
      end
    end

    def update
      if @user.update(user_params)
        redirect_to edit_admin_user_path(@user), notice: I18n.t('admin.users.updated') and return
      else
        render :edit
      end
    end

    def destroy
      User.transaction do
        @user.surveys.update_all(owner_id: User.deleted_user)
        @user.survey_answers.update_all(user_id: User.deleted_user)
        @user.destroy
      end

      redirect_to admin_users_path, notice: I18n.t('admin.users.deleted')
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params[:user] ||= params[:survey_owner] || params[:admin_user]
      params.require(:user).permit(:first_name, :last_name, :user, :password, :password_confirmation, :type, :email, { token_group_ids: [] })
    end
  end
end

app/views/admin/users/edit.html.erb
<%= simple_nested_form_for @user, as: :user, url: admin_user_path(@user.id), method: :put, html: { class: 'col-lg-6' } do |f| %>

  <%= f.input :email %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :type, collection: User::TYPES, include_blank: false %>

  <div class='panel panel-default'>

    <div class='panel-heading'><%= t('.groups') %></div>

    <div class='panel-body'>

    <input name='user[token_group_ids][]' class='group-autocomplete' type='text' data-pre="<%= @user.groups.to_json %>">

    </div>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/admin/users/index.html.erb
<div class='buttons-panel'>
  <%= link_to new_admin_user_path do %>
    <span class='btn btn-success'><%= t('.new_user') %></span>
  <% end %>
</div>

<div>
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th><%= t('.first_name') %></th>
          <th><%= t('.last_name') %></th>
          <th><%= t('.email') %></th>
          <th><%= t('.type') %></th>
          <th><%= t(:edit) %></th>
          <th><%= t(:delete) %></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% if !user.deleted_user? %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user_display_email(user) %></td>
              <td><%= user.type %></td>
              <td><%= link_to t(:edit), edit_admin_user_path(user) %></td>
              <td>
                  <%= current_user != user ? link_to(t(:delete), "users/#{user.id}", method: :delete, data: { confirm: t(:are_you_sure) }) : '-' %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

  </div>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/users/new.html.erb
<%= simple_nested_form_for @user, as: :user, url: admin_users_path, method: :post, html: { class: 'col-lg-6' } do |f| %>

  <%= f.input :email %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :type, collection: User::TYPES, include_blank: false %>

  <div class='panel panel-default'>

    <div class='panel-heading'><%= t('.groups') %></div>

    <div class='panel-body'>

    <input name='user[token_group_ids][]' class='group-autocomplete' type='text' data-pre="<%= @user.groups.to_json %>">

    </div>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/admin/users/show.html.erb
<%= @user.email %>
<%= @user.last_name %>